version: '3.2'
services:

  website:
    build:
      context: ./website
      args:
        REACT_APP_BACKEND_URL: http://localhost:8080
    ports:
      - 80:80
    environment:
      - AUTH_URL=http://auth-micro:8080/login
      - CALLBACK_URL=http://auth-micro:8080/callback

  auth-micro:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        project: ./cmd/auth/
    env_file:
      ./auth.env
    environment:
      - REDIRECT_URL=http://localhost/callback
      - FRONT_URL=http://localhost
      - ACCESS_SECRET=thisisnotproductionlulz
      - STATE_SECRET=thisisnotproductionlulz111111111


  backend:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        project: ./cmd/backend/
    environment:
      - RANDOM_MICRO_SERVICE_HOST=random-micro
      - RANDOM_MICRO_SERVICE_PORT=8081
      - CHARACTER_MICRO_SERVICE_HOST=character-micro
      - CHARACTER_MICRO_SERVICE_PORT=8081
      - AUTH_MICRO_SERVICE_HOST=auth-micro
      - AUTH_MICRO_SERVICE_PORT=8081
      - FRONT_URL=http://localhost
    ports:
      - 8080:8080
    depends_on:
      - random-micro

  character-micro:
      build:
        context: .
        dockerfile: ./build/Dockerfile
        args:
          project: ./cmd/characters/

  random-micro:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        project: ./cmd/random-micro/

  
  #db1:
  #    container_name: db1
  #    image: cockroachdb/cockroach:latest
  #    volumes:
  #        - ./data/db_1:/cockroach/cockroach-data
  #    command: start --insecure
  #    ports:
  #        - "26257:26257"
  #        - "8080:8080"
  #    networks:
  #        cockroachdb_net:
  #            aliases:
  #                - db_1

  #db2:
  #    container_name: db2
  #    image: cockroachdb/cockroach:latest
  #    volumes:
  #        - ./data/db_2:/cockroach/cockroach-data
  #    command: start --insecure --join=db_1
  #    networks:
  #        cockroachdb_net:
  #            aliases:
  #                - db_2

networks:
    cockroachdb_net:
        driver: bridge