version: '3.2'
services:

  website:
    build:
      context: ../website
    ports:
      - 443:443
    volumes:
      - ../tls:/tls:ro
    depends_on:
      - auth-micro.default.svc.cluster.local
      - backend.default.svc.cluster.local

  auth-micro.default.svc.cluster.local:
    build:
      context: ../
      dockerfile: ./build/Dockerfile
      args:
        project: ./cmd/auth/
    env_file:
      ../auth.env
    environment:
      - REDIRECT_URL=https://localhost/callback
      - FRONT_URL=https://localhost
      - ACCESS_SECRET=thisisnotproductionlulz
      - STATE_SECRET=thisisnotproductionlulz111111111
    volumes:
      - ../tls:/tls:ro
    depends_on:
      - my-release-cockroachdb-public.default.svc.cluster.local


  backend.default.svc.cluster.local:
    build:
      context: ../
      dockerfile: ./build/Dockerfile
      args:
        project: ./cmd/backend/
    environment:
      - FRONT_URL=https://localhost
    volumes:
      - ../tls:/tls:ro
    ports:
      - 8080:8080
    depends_on:
      - random-micro.default.svc.cluster.local
      - my-release-cockroachdb-public.default.svc.cluster.local
      - auth-micro.default.svc.cluster.local

  character-micro.default.svc.cluster.local:
    build:
      context: ../
      dockerfile: ./build/Dockerfile
      args:
        project: ./cmd/characters/
    volumes:
      - ../tls:/tls:ro

  random-micro.default.svc.cluster.local:
    build:
      context: ../
      dockerfile: ./build/Dockerfile
      args:
        project: ./cmd/random-micro/
    volumes:
      - ../tls:/tls:ro

  my-release-cockroachdb-public.default.svc.cluster.local:
      image: cockroachdb/cockroach:latest
      volumes:
          - ./data/db:/cockroach/cockroach-data
      command: start-single-node --insecure
      ports:
          - "8082:8080"

networks:
    cockroachdb_net:
        driver: bridge