version: '3.2'
services:

  website:
    build:
      context: ../website
      args:
        REACT_APP_BACKEND_URL: http://localhost:8080
    ports:
      - 80:80
      - 443:443
    environment:
      - AUTH_URL=http://auth-micro:8080/login
      - CALLBACK_URL=http://auth-micro:8080/callback
    volumes:
      - ../tls:/tls:ro
    depends_on:
      - auth-micro
      - backend

  auth-micro:
    build:
      context: ../
      dockerfile: ./build/Dockerfile
      args:
        project: ./cmd/auth/
    env_file:
      ../auth.env
    environment:
      - REDIRECT_URL=https://localhost/callback
      - FRONT_URL=https://localhost
      - ACCESS_SECRET=thisisnotproductionlulz
      - STATE_SECRET=thisisnotproductionlulz111111111
    volumes:
      - ../tls:/tls:ro
    depends_on:
      - my-release-cockroachdb-public.default.svc.cluster.local


  backend:
    build:
      context: ../
      dockerfile: ./build/Dockerfile
      args:
        project: ./cmd/backend/
    environment:
      - RANDOM_MICRO_SERVICE_HOST=random-micro
      - RANDOM_MICRO_SERVICE_PORT=8081
      - CHARACTER_MICRO_SERVICE_HOST=character-micro
      - CHARACTER_MICRO_SERVICE_PORT=8081
      - AUTH_MICRO_SERVICE_HOST=auth-micro
      - AUTH_MICRO_SERVICE_PORT=8081
      - FRONT_URL=https://localhost
    volumes:
      - ../tls:/tls:ro
    ports:
      - 8080:8080
    depends_on:
      - random-micro
      - my-release-cockroachdb-public.default.svc.cluster.local
      - auth-micro

  character-micro:
    build:
      context: ../
      dockerfile: ./build/Dockerfile
      args:
        project: ./cmd/characters/
    volumes:
      - ../tls:/tls:ro

  random-micro:
    build:
      context: ../
      dockerfile: ./build/Dockerfile
      args:
        project: ./cmd/random-micro/
    volumes:
      - ../tls:/tls:ro

  my-release-cockroachdb-public.default.svc.cluster.local:
      image: cockroachdb/cockroach:latest
      volumes:
          - ./data/db:/cockroach/cockroach-data
      command: start-single-node --insecure
      ports:
          - "8082:8080"

networks:
    cockroachdb_net:
        driver: bridge