version: '3.2'
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/backend/
    environment:
      - RANDOM_MICRO_SERVICE_HOST=random-micro
      - RANDOM_MICRO_SERVICE_PORT=8080
      - CHARACTER_MICRO_SERVICE_HOST=character-micro
      - CHARACTER_MICRO_SERVICE_PORT=8080
    ports:
      - 8081:8080
    depends_on:
      - random-micro

  character-micro:
      build:
        context: .
        dockerfile: ./Dockerfile
        args:
          project: ./cmd/characters/

  random-micro:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/random-micro/

  
  #db1:
  #    container_name: db1
  #    image: cockroachdb/cockroach:latest
  #    volumes:
  #        - ./data/db_1:/cockroach/cockroach-data
  #    command: start --insecure
  #    ports:
  #        - "26257:26257"
  #        - "8080:8080"
  #    networks:
  #        cockroachdb_net:
  #            aliases:
  #                - db_1

  #db2:
  #    container_name: db2
  #    image: cockroachdb/cockroach:latest
  #    volumes:
  #        - ./data/db_2:/cockroach/cockroach-data
  #    command: start --insecure --join=db_1
  #    networks:
  #        cockroachdb_net:
  #            aliases:
  #                - db_2

networks:
    cockroachdb_net:
        driver: bridge