version: '3.2'
services:
  backend:
    build: ./backend
    ports:
      - "8081:8080"

  random:
    build: ./random-micro
    ports:
      - "8082:8080"

  db1:
      container_name: db1
      image: cockroachdb/cockroach:latest
      volumes:
          - ./data/db_1:/cockroach/cockroach-data
      command: start --insecure
      ports:
          - "26257:26257"
          - "8080:8080"
      networks:
          cockroachdb_net:
              aliases:
                  - db_1

  db2:
      container_name: db2
      image: cockroachdb/cockroach:latest
      volumes:
          - ./data/db_2:/cockroach/cockroach-data
      command: start --insecure --join=db_1
      networks:
          cockroachdb_net:
              aliases:
                  - db_2

networks:
    cockroachdb_net:
        driver: bridge