apiVersion: v1
kind: Service
metadata:
  name: auth-micro
spec:
  selector:
    app: auth-micro
  ports:
    - name: grpc
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: auth-micro
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: auth-micro
    spec:
      containers:
      - name: auth-micro
        image: gcr.io/PROJECT_ID/AUTH:TAG
        env:
          - name: ACCESS_SECRET
            valueFrom:
              secretKeyRef:
                name: secrets
                key: access.txt
          - name: STATE_SECRET
            valueFrom:
              secretKeyRef:
                name: secrets
                key: state.txt
        ports:
        - containerPort: 8081
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
        volumeMounts:
        - mountPath: "/tls"
          name: secret
          readOnly: true
      volumes:
        - name: secret
          secret:
            secretName: test-tls