apiVersion: v1
kind: Service
metadata:
  name: auth-micro
spec:
  selector:
    app: auth-micro
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: auth-micro
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: auth-micro
    spec:
      containers:
      - name: auth-micro
        image: gcr.io/PROJECT_ID/AUTH:TAG
        env:
        - name: DB_SERVICE_HOST
          value: "my-release-cockroachdb-public.default.svc.cluster.local"
        - name: DB_SERVICE_PORT
          value: "26257"
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
        volumeMounts:
        - mountPath: "/tls"
          name: secret
          readOnly: true
      volumes:
        - name: secret
          secret:
            secretName: test-tls