// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	character "github.com/hectorgabucio/donotdevelopmyapp/internal/character"

	mock "github.com/stretchr/testify/mock"
)

// CharacterServiceServer is an autogenerated mock type for the CharacterServiceServer type
type CharacterServiceServer struct {
	mock.Mock
}

// GetCharacter provides a mock function with given fields: _a0, _a1
func (_m *CharacterServiceServer) GetCharacter(_a0 context.Context, _a1 *character.Input) (*character.Output, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *character.Output
	if rf, ok := ret.Get(0).(func(context.Context, *character.Input) *character.Output); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*character.Output)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *character.Input) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
