// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"

	character "github.com/hectorgabucio/donotdevelopmyapp/internal/character"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// CharacterServiceClient is an autogenerated mock type for the CharacterServiceClient type
type CharacterServiceClient struct {
	mock.Mock
}

// GetCharacter provides a mock function with given fields: ctx, in, opts
func (_m *CharacterServiceClient) GetCharacter(ctx context.Context, in *character.Input, opts ...grpc.CallOption) (*character.Output, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *character.Output
	if rf, ok := ret.Get(0).(func(context.Context, *character.Input, ...grpc.CallOption) *character.Output); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*character.Output)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *character.Input, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
