// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Cipher is an autogenerated mock type for the Cipher type
type Cipher struct {
	mock.Mock
}

// Decrypt provides a mock function with given fields: key, data
func (_m *Cipher) Decrypt(key []byte, data []byte) ([]byte, error) {
	ret := _m.Called(key, data)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte, []byte) []byte); ok {
		r0 = rf(key, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = rf(key, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Encrypt provides a mock function with given fields: key, data
func (_m *Cipher) Encrypt(key []byte, data []byte) ([]byte, error) {
	ret := _m.Called(key, data)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte, []byte) []byte); ok {
		r0 = rf(key, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = rf(key, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
