// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	random "github.com/hectorgabucio/donotdevelopmyapp/internal/random"
	mock "github.com/stretchr/testify/mock"
)

// RandomServiceServer is an autogenerated mock type for the RandomServiceServer type
type RandomServiceServer struct {
	mock.Mock
}

// GetRandom provides a mock function with given fields: _a0, _a1
func (_m *RandomServiceServer) GetRandom(_a0 context.Context, _a1 *random.RandomInput) (*random.RandomNumber, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *random.RandomNumber
	if rf, ok := ret.Get(0).(func(context.Context, *random.RandomInput) *random.RandomNumber); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*random.RandomNumber)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *random.RandomInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
