// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	random "github.com/hectorgabucio/donotdevelopmyapp/internal/random"
)

// RandomServiceClient is an autogenerated mock type for the RandomServiceClient type
type RandomServiceClient struct {
	mock.Mock
}

// GetRandom provides a mock function with given fields: ctx, in, opts
func (_m *RandomServiceClient) GetRandom(ctx context.Context, in *random.RandomInput, opts ...grpc.CallOption) (*random.RandomNumber, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *random.RandomNumber
	if rf, ok := ret.Get(0).(func(context.Context, *random.RandomInput, ...grpc.CallOption) *random.RandomNumber); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*random.RandomNumber)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *random.RandomInput, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
