// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	data "github.com/hectorgabucio/donotdevelopmyapp/internal/data"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// AddCharacterToUser provides a mock function with given fields: character, userId
func (_m *UserRepository) AddCharacterToUser(character *data.Character, userId string) error {
	ret := _m.Called(character, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(*data.Character, string) error); ok {
		r0 = rf(character, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CloseConn provides a mock function with given fields:
func (_m *UserRepository) CloseConn() {
	_m.Called()
}

// GetOrCreate provides a mock function with given fields: userResult, userWhere
func (_m *UserRepository) GetOrCreate(userResult *data.User, userWhere *data.User) error {
	ret := _m.Called(userResult, userWhere)

	var r0 error
	if rf, ok := ret.Get(0).(func(*data.User, *data.User) error); ok {
		r0 = rf(userResult, userWhere)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
