on: [push, pull_request]
name: Go test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make cov
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
      file: ./coverage.txt # optional