on: [push, pull_request]
name: React test
jobs:
  frontTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: make test-front